package com.hackathon.server.models.enums;

public enum AccessNeedENUM {

    ADHD,
    DYSLEXIA,
    ASD,
    ALZHEIMERS,
    EPILEPSY,
    BLINDNESS,
    LOW_VISION,
    COLOUR_BLINDNESS,
    TUNNEL_VISION,
    MACULAR_DEGENERATION,
    RETINITIS_PIGMENTOSA,
    DEAFNESS,
    HARD_OF_HEARING,
    AUDITORY_PROCESSING,
    MOBILITY
}
